name: Continuous Integration

on:
  pull_request:
  push:
    branches: master

jobs:
  rust-check:
    name: Rust check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: check

  rust-test:
    name: Rust test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
              ffmpeg \
              gir1.2-gtk-3.0 \
              libdconf-dbus-1-dev \
              libfftw3-dev \
              libgirepository1.0-dev \
              libmpv-dev \
              libnss3 \
              libpulse-dev \
              pulseaudio \
              xvfb
      - uses: actions-rs/cargo@v1
        with:
          command: test --no-default-features

  rust-fmt:
    name: Rust fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  rust-clippy:
    name: Rust clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
    

  python-tests:
    name: Python tests
    runs-on: ubuntu-latest
    strategy:
        matrix:
            python: [3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
              ffmpeg \
              gir1.2-gtk-3.0 \
              libdconf-dbus-1-dev \
              libfftw3-dev \
              libgirepository1.0-dev \
              libmpv-dev \
              libnss3 \
              libpulse-dev \
              pulseaudio \
              xvfb
          pip install .
      - name: Run Tests
        run: sh dev/run-python-tests.sh

  python-linter:
      name: Python linter
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v1
          with:
            python-version: '3.x'
        - name: Install Linter
          run: python3 -m pip install flake8
        - name: Run Linter
          run: python3 -m flake8 . --ignore='F821,W503,E731'
